/**
 * Tokens visuais — Clinical Soft Dashboard
 * Usados apenas no dashboard do médico.
 */
export const clinicalSoftTokens = {
  colors: {
    background: '#F8FAFC',
    surface: '#FFFFFF',
    primary: '#0EA5E9',
    primaryDark: '#0369A1',
    primaryDarkDeep: '#0C4A6E',
    secondary: '#64748B',
    tertiary: '#94A3B8',
    success: '#22C55E',
    warning: '#F59E0B',
    danger: '#EF4444',
    accentAI: '#8B5CF6',
    dangerLight: '#FEF2F2',
    successLight: '#F0FDF4',
    infoLight: '#F0F9FF',
    warningLight: '#FFFBEB',
    warningBg: '#FFFBEB',
    warningAccent: '#F59E0B',
    // Queue card (dark gradient)
    queueGradient: ['#0C4A6E', '#075985'] as const,
    queueIconOuter: 'rgba(255,255,255,0.15)',
    queueIconInner: 'rgba(255,255,255,0.25)',
    queueButtonBg: 'rgba(255,255,255,0.2)',
    queueButtonBorder: 'rgba(255,255,255,0.3)',
    queueButtonText: '#FFFFFF',
    // Stat card accent colors
    statPendentes: '#F59E0B',
    statConcluidos: '#22C55E',
    statReceitas: '#0EA5E9',
    statConsultas: '#8B5CF6',
    // Shadows
    shadowColor: '#94A3B8',
    shadowColorAlt: '#64748B',
  },
  radius: {
    banner: 12,
    card: 16,
    hero: 16,
    nav: 16,
    button: 14,
    iconBox: 12,
    iconBoxSmall: 10,
  },
  spacing: {
    screen: 16,
    block: 20,
    card: 16,
  },
  shadow: {
    card: {
      shadowColor: '#94A3B8',
      shadowOpacity: 0.08,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    queueButton: {
      shadowColor: '#000000',
      shadowOpacity: 0.1,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    quickButton: {
      shadowColor: '#94A3B8',
      shadowOpacity: 0.08,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    avatar: {
      shadowColor: '#64748B',
      shadowOpacity: 0.12,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 3,
    },
  },
  typography: {
    greeting: { fontSize: 13, lineHeight: 18, fontWeight: '400' as const },
    name: { fontSize: 22, lineHeight: 28, fontWeight: '700' as const },
    date: { fontSize: 12, lineHeight: 16, fontWeight: '400' as const },
    sectionTitle: { fontSize: 16, lineHeight: 20, fontWeight: '700' as const },
    queueTitle: { fontSize: 11, lineHeight: 14, fontWeight: '700' as const, letterSpacing: 1.0 },
    queueText: { fontSize: 28, lineHeight: 34, fontWeight: '700' as const },
    queueButton: { fontSize: 13, fontWeight: '700' as const },
    statTitle: { fontSize: 12, lineHeight: 16, fontWeight: '600' as const },
    statValue: { fontSize: 26, lineHeight: 32, fontWeight: '700' as const },
    quickLabel: { fontSize: 12, lineHeight: 16, fontWeight: '600' as const },
    bannerText: { fontSize: 13, fontWeight: '500' as const },
  },
};
