/**
 * Tokens visuais — Clinical Soft Dashboard
 * Usados apenas no dashboard do médico.
 */
export const clinicalSoftTokens = {
  colors: {
    background: '#F6F8FC',
    surface: '#FFFFFF',
    primary: '#28A7F0',
    primaryDark: '#17365D',
    secondary: '#5A6F87',
    success: '#35BE68',
    danger: '#FF5E63',
    dangerLight: '#FCEEEF',
    successLight: '#EEF8F0',
    infoLight: '#EEF6FC',
    warningBg: '#FFF4E7',
    warningAccent: '#F2A100',
    queueGradient: ['#EEF8FF', '#EAF6FF'] as const,
    queueIconOuter: '#BFE6FF',
    queueIconInner: '#2AAEF4',
    queueButtonBg: '#F9FCFF',
    queueButtonBorder: '#D8E9F7',
    queueButtonText: '#2099E8',
    shadowColor: '#BFCBDA',
    shadowColorAlt: '#AAB7CA',
  },
  radius: {
    banner: 14,
    card: 24,
    hero: 28,
    nav: 28,
    button: 24,
    iconBox: 18,
    iconBoxSmall: 14,
  },
  spacing: {
    screen: 16,
    block: 22,
    card: 20,
  },
  shadow: {
    card: {
      shadowColor: '#BFCBDA',
      shadowOpacity: 0.16,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
    queueButton: {
      shadowColor: '#C7D7E9',
      shadowOpacity: 0.15,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      elevation: 2,
    },
    quickButton: {
      shadowColor: '#BFCBDA',
      shadowOpacity: 0.14,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
    avatar: {
      shadowColor: '#AAB7CA',
      shadowOpacity: 0.16,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 8 },
      elevation: 4,
    },
  },
  typography: {
    greeting: { fontSize: 26, lineHeight: 31, fontWeight: '400' as const },
    name: { fontSize: 26, lineHeight: 31, fontWeight: '800' as const },
    date: { fontSize: 15, lineHeight: 21, fontWeight: '400' as const },
    sectionTitle: { fontSize: 22, lineHeight: 26, fontWeight: '800' as const },
    queueTitle: { fontSize: 22, lineHeight: 27, fontWeight: '800' as const },
    queueText: { fontSize: 16, lineHeight: 23, fontWeight: '400' as const },
    queueButton: { fontSize: 16, fontWeight: '700' as const },
    statTitle: { fontSize: 16, lineHeight: 21, fontWeight: '700' as const },
    statValue: { fontSize: 28, lineHeight: 31, fontWeight: '800' as const },
    quickLabel: { fontSize: 14, lineHeight: 17, fontWeight: '600' as const },
    bannerText: { fontSize: 14, fontWeight: '500' as const },
  },
};
